$lock_cmd = hyprctl dispatch 'hl.dsp.global("quickshell:lock")' & pidof qs quickshell hyprlock || hyprlock
# $lock_cmd = pidof hyprlock || hyprlock
$unlock_cmd = hyprctl dispatch 'hl.dsp.global("quickshell:unlock")'
$suspend_cmd = systemctl suspend || loginctl suspend

general {
    lock_cmd = $lock_cmd
    unlock_cmd = $unlock_cmd
    before_sleep_cmd = loginctl lock-session
    # Force reload ensures that the lockscreen is not stuck on first frame.
    # Issue seems to be with both Hyprland and Quickshell:
    # Hyprland drops the first frame after resume, and Quickshell stops drawing
    # because it didn't receive callback from compositor.
    # Or it could just be NVIDIA being NVIDIA on my setup i dunno, the fix is all that matters
    after_sleep_cmd = sleep 1; hyprctl dispatch 'hl.dsp.force_renderer_reload()'; hyprctl dispatch 'hl.dsp.global("quickshell:lockFocus")'
    inhibit_sleep = 3
}

listener {
    timeout = 300 # 5mins
    on-timeout = loginctl lock-session
}

listener {
    timeout = 600 # 10mins
    on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })'
    on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
}

listener {
    timeout = 900 # 15mins
    on-timeout = $suspend_cmd
}
